name: "upload-spm"
description: "Upload pre-compiled SQLite extension to a Github Release in an spm-compatible way"
author: "Alex Garcia"
inputs:
  name:
    description: "Name of your SPM project, ex 'sqlite-foo'"
    required: true
  github-token:
    description: "Github API Token used to upload release assets, which is probably secrets.GITHUB_TOKEN "
    required: true
  platforms:
    description: "TODO"
    required: true
  asset-name-template:
    description: "TODO"
    required: false
    default: "$PROJECT-$VERSION-loadable-$OS-$CPU"
  skip-spm:
    description: "TODO"
    required: false
runs:
  using: "node16"
  main: "dist/index.js"
